import {getAppConfig} from '@/config/index';
import {getModelContextLimit, getSessionContextLimit} from '@/models/index';
import {runLifecycleHooks} from '@/services/lifecycle-hooks';
import {createTokenizer} from '@/tokenization/index';
import type {
	CompressionMode,
	CompressionStrategy,
	TuneConfig,
} from '@/types/config';
import type {AISDKCoreTool, LLMClient, Message} from '@/types/core';
import type {Tokenizer} from '@/types/tokenization';
import {calculateToolDefinitionsTokensFromDefs} from '@/usage/calculator';
import {getLogger} from '@/utils/logging';
import {bumpReadContentGeneration} from '@/utils/read-tracker';
import {
	autoCompactSessionOverrides,
	resetAutoCompactSession as resetAutoCompactSessionOverrides,
} from './auto-compact-session';
import {compressionBackup} from './compression-backup';
import {summariseWithLLM} from './llm-summariser';
import {COMPRESSION_CONSTANTS, compressMessages} from './message-compression';
import {filterModelFacing} from './message-visibility';

export {
	autoCompactSessionOverrides,
	setAutoCompactEnabled,
	setAutoCompactMode,
	setAutoCompactStrategy,
	setAutoCompactThreshold,
} from './auto-compact-session';

// Tune's "Aggressive Compact" preset. It sits between the config file and the
// user's explicit `/compact` session overrides, so turning tune on or off never
// clobbers a threshold or mode the user set by hand.
let tuneAggressiveCompact = false;

/** Threshold used by tune's aggressive compact (the lowest supported value). */
export const AGGRESSIVE_COMPACT_THRESHOLD =
	COMPRESSION_CONSTANTS.MIN_THRESHOLD_PERCENT;

/**
 * Apply (or clear) tune's aggressive-compact preset from a resolved tune config.
 * Call whenever the active tune changes, including at startup.
 */
export function applyTuneCompaction(tune: TuneConfig | undefined): void {
	tuneAggressiveCompact = Boolean(tune?.enabled && tune.aggressiveCompact);
}

export interface ResolvedAutoCompactSettings {
	enabled: boolean;
	threshold: number;
	mode: CompressionMode;
	strategy: CompressionStrategy;
	hasOverrides: boolean;
}

/**
 * Resolve the effective auto-compact settings.
 * Precedence: `/compact` session override > tune aggressive compact > config.
 */
export function resolveAutoCompactSettings(config: {
	enabled: boolean;
	threshold: number;
	mode: CompressionMode;
	strategy?: CompressionStrategy;
}): ResolvedAutoCompactSettings {
	const session = autoCompactSessionOverrides;
	const tuneThreshold = tuneAggressiveCompact
		? AGGRESSIVE_COMPACT_THRESHOLD
		: null;
	const tuneMode: CompressionMode | null = tuneAggressiveCompact
		? 'aggressive'
		: null;
	return {
		enabled: session.enabled ?? config.enabled,
		threshold: session.threshold ?? tuneThreshold ?? config.threshold,
		mode: session.mode ?? tuneMode ?? config.mode,
		strategy: session.strategy ?? config.strategy ?? 'llm',
		hasOverrides:
			session.enabled !== null ||
			session.threshold !== null ||
			session.mode !== null ||
			tuneAggressiveCompact,
	};
}

/**
 * Perform auto-compact on messages (async)
 * Returns compressed messages if compression was performed, null otherwise.
 *
 * When `strategy` resolves to 'llm' and a client is provided, the compressible
 * segment is replaced by a single synthetic message generated by the model.
 * Falls back to the mechanical path on any LLM error.
 *
 * `nativeTools` are the tool definitions sent to the model out-of-band (native
 * tool calling). They occupy context but live outside the message list, so the
 * trigger would under-count without them and fire late — mirror the context
 * indicator by adding their token cost to the gate. Pass `{}`/undefined under
 * XML/JSON fallback, where the definitions are already inside `systemMessage`.
 */
export async function performAutoCompact(
	messages: Message[],
	systemMessage: Message,
	provider: string,
	model: string,
	config: {
		enabled: boolean;
		threshold: number;
		mode: CompressionMode;
		strategy?: CompressionStrategy;
		notifyUser: boolean;
	},
	onNotify?: (message: string) => void,
	client?: LLMClient,
	nativeTools?: Record<string, AISDKCoreTool>,
	signal?: AbortSignal,
): Promise<Message[] | null> {
	if (signal?.aborted) {
		return null;
	}

	const {enabled, threshold, mode, strategy} =
		resolveAutoCompactSettings(config);

	if (!enabled) {
		return null;
	}

	// Get context limit: session override takes priority
	let contextLimit: number | null;
	const sessionLimit = getSessionContextLimit();
	if (sessionLimit !== null) {
		contextLimit = sessionLimit;
	} else {
		try {
			contextLimit = await getModelContextLimit(model, {
				providerConfig: client?.getProviderConfig(),
			});
		} catch {
			return null;
		}
	}

	if (!contextLimit) {
		return null;
	}

	if (signal?.aborted) {
		return null;
	}

	// Create tokenizer
	let tokenizer: Tokenizer | undefined;
	try {
		tokenizer = createTokenizer(provider, model);
	} catch {
		return null;
	}

	try {
		// Calculate current token count. Display-only notices are filtered out of
		// the provider payload, so counting them would trip the threshold on
		// tokens the model never receives — but they stay in `allMessages`, which
		// is what compaction rewrites and the UI renders.
		const allMessages = [systemMessage, ...messages];
		let messageTokens = 0;
		for (const msg of filterModelFacing(allMessages)) {
			messageTokens += tokenizer.countTokens(msg);
		}

		// Native tool definitions occupy context but aren't in the message list
		// (under XML/JSON fallback callers pass nothing because the definitions are
		// already baked into systemMessage). Adding them keeps the trigger aligned
		// with the displayed ctx% so it doesn't fire late on tool-heavy setups.
		const toolDefTokens = nativeTools
			? calculateToolDefinitionsTokensFromDefs(nativeTools, tokenizer)
			: 0;
		const totalTokens = messageTokens + toolDefTokens;

		// Check if threshold is reached
		const usagePercentage = (totalTokens / contextLimit) * 100;
		if (usagePercentage < threshold) {
			return null;
		}

		// Last chance for a hook to see the pre-compaction conversation (e.g.
		// archive it). Observe-only: pre-compact cannot veto compaction, since
		// refusing it would leave the context over the model's limit.
		await runLifecycleHooks('pre-compact', {messageCount: messages.length});

		compressionBackup.storeBackup(messages);

		// LLM strategy: ask the model to summarise the compressible segment into
		// a single synthetic message. Falls back to mechanical on any failure
		// (network error, malformed response, etc.) so a transient model issue
		// never blocks compaction.
		if (strategy === 'llm' && client) {
			if (signal?.aborted) {
				return null;
			}
			if (config.notifyUser && onNotify) {
				onNotify('auto-compacting context...');
			}
			try {
				const llmCompressed = await summariseWithLLM({
					messages,
					systemMessage,
					client,
					tokenizer,
					signal,
				});

				if (signal?.aborted) {
					return null;
				}

				if (llmCompressed) {
					// Tool definitions are constant across compaction, so include them on
					// both sides — otherwise the reduction % is inflated by tokens that
					// never get removed.
					const compressedTokenCount =
						[systemMessage, ...filterModelFacing(llmCompressed)].reduce(
							(sum, msg) => sum + tokenizer.countTokens(msg),
							0,
						) + toolDefTokens;
					const reductionPercentage =
						totalTokens > 0
							? ((totalTokens - compressedTokenCount) / totalTokens) * 100
							: 0;

					if (config.notifyUser && onNotify) {
						const reduction = Math.round(reductionPercentage);
						onNotify(
							`Context at ${Math.round(usagePercentage)}% capacity - auto-compacting (LLM summary)...\n\nContext Compacted: ${totalTokens.toLocaleString()} tokens → ${compressedTokenCount.toLocaleString()} tokens (${reduction}% reduction)`,
						);
					}

					bumpReadContentGeneration();
					return llmCompressed;
				}
			} catch (_error) {
				if (signal?.aborted) {
					return null;
				}
				// fall through to mechanical
			}
		}

		if (signal?.aborted) {
			return null;
		}

		// Include system message in compression input so compressMessages()
		// preserves it and only compresses user/assistant/tool messages — matching
		// the behaviour of manual `/compact`.
		const result = compressMessages(allMessages, tokenizer, {mode});

		// Filter out system messages from the compressed output (they are re-injected
		// by the chat handler on each LLM call)
		const compressedUserMessages = result.compressedMessages.filter(
			msg => msg.role !== 'system',
		);

		// Show notification if enabled
		if (config.notifyUser && onNotify) {
			const reduction = Math.round(result.reductionPercentage);
			onNotify(
				`Context at ${Math.round(usagePercentage)}% capacity - auto-compacting...\n\nContext Compacted: ${result.originalTokenCount.toLocaleString()} tokens → ${result.compressedTokenCount.toLocaleString()} tokens (${reduction}% reduction)`,
			);
		}

		// Return compressed user messages (without system message)
		bumpReadContentGeneration();
		return compressedUserMessages;
	} finally {
		// Clean up tokenizer
		if (tokenizer?.free) {
			tokenizer.free();
		}
	}
}

export async function maybeAutoCompact(
	messages: Message[],
	systemMessage: Message,
	client: LLMClient,
	nativeTools?: Record<string, AISDKCoreTool>,
	options?: {
		signal?: AbortSignal;
		onNotify?: (message: string) => void;
		// Callers that already track the active provider/model (the TUI reads
		// them from app state) pass them explicitly. Everything else derives
		// them from the client.
		provider?: string;
		model?: string;
	},
): Promise<Message[]> {
	if (options?.signal?.aborted) {
		return messages;
	}

	const autoCompactConfig = getAppConfig().autoCompact;
	if (!autoCompactConfig) {
		return messages;
	}

	try {
		const compressed = await performAutoCompact(
			messages,
			systemMessage,
			options?.provider ?? client.getProviderConfig().name,
			options?.model ?? client.getCurrentModel(),
			autoCompactConfig,
			options?.onNotify,
			client,
			nativeTools,
			options?.signal,
		);
		return compressed ?? messages;
	} catch (error) {
		getLogger().debug('auto-compact failed; leaving history unchanged', error);
		return messages;
	}
}

// Set session override helpers live in `./auto-compact-session` (a
// lightweight module without the tokenizer/config graph, so the inline
// `?key=value` parser specs can import them without timing out). They are
// re-exported above so existing importers keep working.
//
// `resetAutoCompactSession` is defined (not re-exported) here because it
// additionally clears tune's aggressive-compact preset.
export function resetAutoCompactSession(): void {
	resetAutoCompactSessionOverrides();
	tuneAggressiveCompact = false;
}
