/**
 * Single source of truth for the shell completion surface of the CLI.
 *
 * The hand-rolled parser in `cli.tsx` and the static `--help` text both
 * describe the same flags; this module adds a third consumer so the bash,
 * zsh, and fish scripts generated by `render.ts` can never silently drift
 * when a flag or subcommand is added. Update THIS file and the completion
 * scripts pick it up; the other two call sites still need a matching edit.
 *
 * Note: in-app slash commands (`/clear`, `/doctor`, …) are deliberately NOT
 * here — they are typed inside the TUI and never reach the shell, so shell
 * completion cannot and should not offer them.
 */

export interface CompletionFlag {
	/** Long name without the leading dashes, e.g. `provider` for `--provider`. */
	name: string;
	/** Short name without the leading dash, e.g. `c` for `-c`. */
	short?: string;
	/** Whether the flag consumes the following token as its value. */
	takesValue: boolean;
	/** Closed set of values offered for completion, when one exists. */
	values?: readonly string[];
	/** Placeholder shown for the value in help-style listings. */
	valueName?: string;
	description: string;
}

export interface CompletionSubcommand {
	name: string;
	description: string;
	/** Nested positional tokens, e.g. `daemon` → `start|stop|…`. */
	children?: readonly string[];
}

export const COMPLETION_SHELLS = ['bash', 'zsh', 'fish'] as const;
export type CompletionShell = (typeof COMPLETION_SHELLS)[number];

export const COMPLETION_SUBCOMMANDS: readonly CompletionSubcommand[] = [
	{
		name: 'init',
		description: 'Analyze the project and create AGENTS.md',
	},
	{
		name: 'run',
		description: 'Run in non-interactive mode',
	},
	{
		name: 'storage',
		description: 'Inspect storage (read-only; --format json for scripts)',
	},
	{
		name: 'daemon',
		description: 'Manage the per-project skill daemon',
		children: ['start', 'stop', 'status', 'logs', 'install', 'uninstall'],
	},
	{
		name: 'config',
		description: 'Inspect the resolved configuration',
		children: ['list', 'show', 'diff'],
	},
	{
		name: 'codex',
		description: 'Log in to ChatGPT/Codex (device flow)',
		children: ['login'],
	},
	{
		name: 'copilot',
		description: 'Log in to GitHub Copilot (device flow)',
		children: ['login'],
	},
	{
		name: 'completion',
		description: 'Generate a shell completion script',
		children: COMPLETION_SHELLS,
	},
];

export const COMPLETION_FLAGS: readonly CompletionFlag[] = [
	{
		name: 'provider',
		takesValue: true,
		valueName: 'provider',
		description:
			'Specify AI provider (must be configured in agents.config.json)',
	},
	{
		name: 'model',
		takesValue: true,
		valueName: 'model',
		description: 'Specify AI model (must be available for the provider)',
	},
	{
		name: 'context-max',
		takesValue: true,
		valueName: 'limit',
		description:
			'Set maximum context length in tokens (supports k/K suffix, e.g. 128k)',
	},
	{
		name: 'mode',
		takesValue: true,
		valueName: 'mode',
		// Keep in step with VALID_MODES in @/app/types. Imported types cannot
		// reach this spec (it is consumed by the completion generators), so a
		// new mode has to be added here by hand or it never tab-completes.
		values: ['normal', 'auto-accept', 'yolo', 'plan', 'architect'],
		description: 'Start in a specific development mode',
	},
	{
		name: 'trust-directory',
		takesValue: false,
		description: 'Skip the first-run directory trust prompt (run mode only)',
	},
	{
		name: 'plain',
		takesValue: false,
		description: 'Use a lightweight, Ink-free runtime (run mode only)',
	},
	{
		name: 'no-plain',
		takesValue: false,
		description: 'Force the Ink runtime even in CI / non-TTY',
	},
	{
		name: 'alt-screen',
		takesValue: false,
		description: 'Fullscreen TUI on the alternate screen buffer',
	},
	{
		name: 'no-alt-screen',
		takesValue: false,
		description: 'Force inline mode (main screen + native scrollback)',
	},
	{
		name: 'json',
		takesValue: false,
		description: 'Output execution results as JSON (run mode only)',
	},
	{
		name: 'output-format',
		takesValue: true,
		valueName: 'format',
		values: ['text', 'json'],
		description: "Specify stdout format ('text' or 'json', run mode only)",
	},
	{
		name: 'acp',
		takesValue: false,
		description: 'Run as an ACP (Agent Client Protocol) server',
	},
	{
		name: 'vscode',
		takesValue: false,
		description: 'Run in VS Code mode',
	},
	{
		name: 'vscode-port',
		takesValue: true,
		valueName: 'port',
		description: 'Specify VS Code port',
	},
	{
		name: 'continue',
		short: 'c',
		takesValue: false,
		description: 'Resume the most recent session for this directory',
	},
	{
		name: 'resume',
		short: 'r',
		takesValue: true,
		valueName: 'id',
		description: 'Resume a session by id or 1-based index',
	},
	{
		name: 'help',
		short: 'h',
		takesValue: false,
		description: 'Show help',
	},
	{
		name: 'version',
		short: 'v',
		takesValue: false,
		description: 'Show version number',
	},
];
